apiVersion: v1
kind: Service
metadata:
  name: test-k8s-svc
  namespace: test-k8s-ns
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
