apiVersion: v1
kind: Service
metadata:
  name: test-k8s-svc
  namespace: test-k8s-ns
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
