apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp
  namespace: k8s-tutorial
spec:
  selector:
    app: kubernetes-bootcamp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
