apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-share
  namespace: default
data:
  index.html: |
    Hello World!

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: share-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: share-files
        configMap:
          name: nginx-share
          items:
          - key: index.html
            path: index.html
