version: "3"
services:
  web:
    image: alpine:latest
    command: ping 127.0.0.1
    networks:
     - frontend
    volumes:
       - share:/data
  middle:
    image: alpine:latest
    command: ping 127.0.0.1
    networks:
      - frontend
      - backend
    volumes:
      - share:/data
  db:
    image: alpine:latest
    command: ping 127.0.0.1
    networks:
      - backend
    volumes:
     - share:/data

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24

volumes:
  share: